import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';

const CONFIG_DIR = join(homedir(), '.snailmountain');
const CONFIG_PATH = join(CONFIG_DIR, 'config.toml');

async function ask(
	rl: ReturnType<typeof createInterface>,
	question: string,
	defaultValue?: string
): Promise<string> {
	const suffix = defaultValue ? ` [${defaultValue}]` : '';
	const answer = await rl.question(`${question}${suffix}: `);
	return answer.trim() || defaultValue || '';
}

export async function runInit(): Promise<void> {
	const rl = createInterface({ input: stdin, output: stdout });

	try {
		console.log('\n🐌 SnailMountain Setup\n');

		if (existsSync(CONFIG_PATH)) {
			const overwrite = await ask(rl, 'Config already exists. Overwrite? (y/N)', 'N');
			if (overwrite.toLowerCase() !== 'y') {
				console.log('Aborted.');
				return;
			}
		}

		// 1. Verify prerequisites
		console.log('\nChecking prerequisites...');
		try {
			execFileSync('gh', ['auth', 'status'], { stdio: 'pipe' });
			console.log('  ✓ GitHub CLI authenticated');
		} catch {
			console.error('  ✗ GitHub CLI not authenticated. Run: gh auth login');
			return;
		}

		try {
			execFileSync('git', ['--version'], { stdio: 'pipe' });
			console.log('  ✓ git available');
		} catch {
			console.error('  ✗ git not found');
			return;
		}

		// 2. Server config
		console.log('\n— Server Configuration —');
		const port = await ask(rl, 'Server port', '3456');
		const maxParallel = await ask(rl, 'Max parallel runs', '2');

		// 3. First repo
		console.log('\n— Add First Repository —');
		const repoName = await ask(rl, 'Repo name (e.g., my-backend)');
		const repoPath = await ask(rl, 'Repo path (absolute)');
		const baseBranch = await ask(rl, 'Base branch', 'main');
		const linearTeamId = await ask(rl, 'Linear team ID for this repo');
		const worktreeDir = await ask(rl, 'Worktree directory', `${repoPath}/../worktrees/${repoName}`);

		if (!repoName || !repoPath || !linearTeamId) {
			console.error('Repo name, path, and Linear team ID are required.');
			return;
		}

		// Verify repo path
		if (!existsSync(join(repoPath, '.git'))) {
			console.warn(`Warning: ${repoPath} does not appear to be a git repository`);
		}

		// 4. Optional: Slack
		console.log('\n— Notifications (optional) —');
		const slackUrl = await ask(rl, 'Slack webhook URL (leave empty to skip)');

		// 5. Generate config
		const configLines = [
			'# SnailMountain configuration',
			'# Generated by snailmountain init',
			'',
			'[server]',
			`port = ${port}`,
			'host = "127.0.0.1"',
			'',
			'[concurrency]',
			`max_parallel = ${maxParallel}`,
			'queue_strategy = "fifo"',
			''
		];

		if (slackUrl) {
			configLines.push(
				'[notifications.slack]',
				`webhook_url = "${slackUrl}"`,
				'notify_on = ["error", "pr_created", "needs_input"]',
				''
			);
		}

		configLines.push(
			`[repos.${repoName}]`,
			`path = "${repoPath}"`,
			`base_branch = "${baseBranch}"`,
			`worktree_dir = "${worktreeDir}"`,
			`linear_team_id = "${linearTeamId}"`,
			'default_model = "sonnet"',
			'default_max_budget_usd = 5.0',
			''
		);

		// 6. Write config
		if (!existsSync(CONFIG_DIR)) {
			mkdirSync(CONFIG_DIR, { recursive: true });
		}
		writeFileSync(CONFIG_PATH, configLines.join('\n'));
		console.log(`\n✓ Config written to ${CONFIG_PATH}`);

		// 7. Remind about .env
		console.log('\n— Next Steps —');
		console.log('1. Set these environment variables in your .env file:');
		console.log('   LINEAR_CLIENT_ID=<your linear oauth app client id>');
		console.log('   LINEAR_CLIENT_SECRET=<your linear oauth app client secret>');
		console.log('   LINEAR_WEBHOOK_SECRET=<your webhook signing secret>');
		console.log('   ANTHROPIC_API_KEY=<your anthropic api key>');
		console.log('');
		console.log('2. Register a Linear webhook pointing to:');
		console.log(`   https://<your-domain>/api/webhook/linear`);
		console.log('');
		console.log('3. Start the server and connect your Linear account at /setup');
		console.log('   pnpm dev');
		console.log('');
		console.log('🐌 Ready to go!');
	} finally {
		rl.close();
	}
}
